Rewrite the SensorFactory
SlimeVR/SlimeVR-Tracker-ESP pull request #122
Opened 2022-03-06 20:42 UTC by TheDevMinerTV

2022-03-07 16:36 UTC, Eirenliel requested changes
Good stuff but needs changes ^^

2022-03-07 21:28 UTC, TheDevMinerTV commented
ℹ️ Ready for QA (again)

2022-03-07 23:34 UTC, TheDevMinerTV commented
ℹ️ Ready for review (again)

2022-03-10 14:11 UTC, Eirenliel requested changes

2022-03-10 14:11 UTC, Eirenliel commented on src/globals.h
> +#define SECOND_IMU IMU_NONE
I don't think it should default to NONE.

2022-03-10 14:11 UTC, Eirenliel commented on src/consts.h
> +#define IMU_NONE 0
I don't think NONE is needed.

2022-03-12 13:26 UTC, Eirenliel requested changes

2022-03-12 13:26 UTC, Eirenliel commented on src/sensors/ErroneousSensor.cpp
> +            Network::sendRotationData(&quaternion, DATA_TYPE_NORMAL, 255, sensorId);
This is not what it needs to send te be displayed, it should just return `SensorStatus::SENSOR_ERROR` in `getSensorState()`, everything else will be handled.

2022-03-12 15:21 UTC, unlogisch04 requested changes
Correct IMU debug text, and move motionLoop to a other position

2022-03-13 14:55 UTC, TheDevMinerTV commented on src/sensors/SensorManager.cpp
> +#if SECOND_IMU == IMU_BNO080 || SECOND_IMU == IMU_BNO085 || SECOND_IMU == IMU_BNO086
Can't happen, this is solved by the redefine in `src/globals.h`

2022-03-14 13:35 UTC, merged