Added option to maximize update rate of ICM on supported boards.
SlimeVR/SlimeVR-Tracker-ESP pull request #145
Opened 2022-04-03 13:27 UTC by ThreadOfFate

Tested on esp8266.
Left off by default as battery life will likely be more noticeable than performance increases.

2022-04-04 13:09 UTC, Eirenliel commented on src/defines.h
> +#define MAX_ODR false // (True) enables Fastest Output Rate (False) caps it to 100Hz (ICM20948 only)
Why is it supported only on WEMOSD1MINI and not on all ESP8266 or actually all boards? Also, defines.h is for defines not for processing, checks should be done in globals.h

2022-04-04 13:10 UTC, Eirenliel commented on src/debug.h
> +
?

2022-04-05 19:58 UTC, TheDevMinerTV requested changes
Same things that Eiren said + some extra

2022-04-05 19:58 UTC, TheDevMinerTV commented on src/sensors/icm20948sensor.cpp
> +    if (USE_6_AXIS)
While you're here, might as well also rewrite those `if`s into preprocessor `#if`s

2022-04-05 19:58 UTC, TheDevMinerTV commented on src/sensors/icm20948sensor.cpp
>      if (USE_6_AXIS)
Would be sweet if you'd also rewrite this one into a `#if` :D

2022-07-21 12:51 UTC, TheDevMinerTV commented
@ThreadOfFate please rebase against `main` and look at the reviews.

2022-11-01 13:56 UTC, closed without merging