Fix i2cscan trying to begin in slave mode
SlimeVR/SlimeVR-Tracker-ESP pull request #153
Opened 2022-04-22 22:32 UTC by sctanf

~Not working, causes esp to crash(?) mid-scan~
Works fine with only i2c wires attached

2022-04-22 22:52 UTC, TheDevMinerTV requested changes
found these issues things

2022-04-22 22:52 UTC, TheDevMinerTV commented on lib/i2cscan/i2cscan.cpp
> +int portArray[] = {16, 5, 4, 2, 14, 12, 13};
explain your reason to change this, there's no pins < 0

2022-04-22 22:52 UTC, TheDevMinerTV commented on lib/i2cscan/i2cscan.cpp
> +int portArray[] = {4, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 32, 33};
same here.

2022-04-22 23:25 UTC, TheDevMinerTV approved these changes

2022-04-23 20:35 UTC, unlogisch04 commented on lib/i2cscan/i2cscan.cpp
> +        Wire.end();
Wire.end(); does not exist in ESP8266
`#ifdef ESP32`
`Wire.end()`
 `#endif`

2022-04-25 23:11 UTC, sctanf commented
Not an issue since trackers are using espressif32 v3.5.0 for now

2022-04-25 23:11 UTC, closed without merging