Fixed some typos
SlimeVR/SlimeVR-Tracker-ESP pull request #194
Opened 2022-09-27 03:57 UTC by Kamilake

Fixed very minor typos :)

2022-10-05 16:34 UTC, Eirenliel commented
That's more than a few typos, it contains some autosleep feature that also doesn't seem to be final. Accidental commit?

2022-10-05 20:07 UTC, TheDevMinerTV requested changes
Hey @Kamilake, please remove the accidental changes or break them up into a separate PR

2022-10-06 13:48 UTC, Kamilake commented
Oops I'm so sorry that's my mistake. I forked the accidentally modified commit and then reverted it

2022-10-06 20:09 UTC, Eirenliel approved these changes

2022-10-06 20:09 UTC, merged