defines.h: Add definition for ESP-WROOM-02
SlimeVR/SlimeVR-Tracker-ESP pull request #279
Opened 2023-09-07 14:52 UTC by medicalwei

This adds definition for ESP-WROOM-02

Tested against a board "WeMos D1 ESP Wroom 02"
![WROOM02_18650](https://github.com/SlimeVR/SlimeVR-Tracker-ESP/assets/74481/bf20d302-880f-4e94-ba74-de0abdfbd6c6)
![20210604071434338](https://github.com/SlimeVR/SlimeVR-Tracker-ESP/assets/74481/f13f9645-826f-45b7-984b-de0941bdcd93)

2023-09-18 14:06 UTC, Eirenliel approved these changes

2023-09-21 18:55 UTC, unlogisch04 commented
Hi, 
Thank you for your commit.
You might want to add that board also in https://github.com/SlimeVR/SlimeVR-Tracker-ESP/blob/main/platformio-tools.ini
To be able to use it in the Webflasher.

2023-09-22 07:36 UTC, medicalwei commented
Squashed the commits and renamed so it's cleaner

2023-09-22 15:43 UTC, unlogisch04 requested changes
As i did look into the board, i was remember ESP-WROOM-02 is the wifi board ifself. So i think it is best to name it different.

2023-09-22 15:43 UTC, unlogisch04 commented on platformio-tools.ini
> +[env:BOARD_WROOM02]
```suggestion
[env:BOARD_WEMOSWROOM02]
```

2023-09-22 15:43 UTC, unlogisch04 commented on src/consts.h
> +#define BOARD_WROOM02 16
```suggestion
#define BOARD_WEMOSWROOM02 16
```

2023-09-22 15:43 UTC, unlogisch04 commented on src/defines.h
> +#elif BOARD == BOARD_WROOM02
```suggestion
#elif BOARD == BOARD_WEMOSWROOM02
```

I dont want to mix it up with the ESP WROOM02 blank module.

2023-09-23 15:19 UTC, unlogisch04 approved these changes

2023-10-01 22:47 UTC, TheDevMinerTV approved these changes
LGTM

@Eirenliel please merge

2023-10-01 22:52 UTC, Eirenliel approved these changes

2023-10-01 22:52 UTC, merged