Fix serial wifi and bwifi. Crash bwifi when no ...
SlimeVR/SlimeVR-Tracker-ESP pull request #298
Opened 2023-10-08 15:37 UTC by unlogisch04

password is provided and add in wifi and bwifi length check of the ssid and password.

2023-10-08 17:35 UTC, TheDevMinerTV requested changes

2023-10-08 19:28 UTC, unlogisch04 commented on src/serial/serialcommands.cpp
> +					}
I do overriead the return so far back in a line. So it helps me to read/understand the code. Also the code was multiline when i did first begin.
Also: https://discord.com/channels/817184208525983775/932240516656029746/1154968426603888751

2023-10-08 22:21 UTC, TheDevMinerTV commented on src/serial/serialcommands.cpp
> +					}
you could've atleast put both checks into the same if

2023-10-08 23:28 UTC, unlogisch04 commented on src/serial/serialcommands.cpp
> +		            }
I did add some. But it was not possible all the way. A other suggestion?

2023-10-08 23:28 UTC, unlogisch04 commented on src/serial/serialcommands.cpp
> +					}
done

2023-10-08 23:35 UTC, unlogisch04 commented on src/serial/serialcommands.h
> + */
i removed it as i not intended to use that outside

2023-10-08 23:36 UTC, unlogisch04 commented on src/serial/serialcommands.cpp
> +		            }
done

2023-10-08 23:37 UTC, unlogisch04 commented on src/serial/serialcommands.cpp
> +			}
reverted as i did not touch that lines.

2023-10-08 23:37 UTC, unlogisch04 commented on src/serial/serialcommands.cpp
> +			}
reverted as i did not touch that lines.

2023-10-08 23:40 UTC, unlogisch04 commented on src/serial/serialcommands.cpp
> +						}
Will not change.

2023-10-12 22:48 UTC, TheDevMinerTV commented on src/serial/serialcommands.h
> +	void setUp();
```suggestion
    void setUp();
```

2023-10-12 22:53 UTC, TheDevMinerTV approved these changes
code looks fine to me

2023-10-13 12:54 UTC, Eirenliel approved these changes

2023-10-13 12:54 UTC, merged