Add threading support
SlimeVR/SlimeVR-Tracker-ESP pull request #320
Opened 2024-03-28 13:15 UTC by nekomona

This patch adds threading for ESP32 variants, allowing more sensors on a single ESP chip.
At current stage, threading mainly separates network packet building and networking stack from sensor operations.

Depending on #314

2024-03-28 13:44 UTC, TheDevMinerTV requested changes
Please double check what changes are actually needed.

2024-03-28 13:44 UTC, TheDevMinerTV commented on src/sensors/sensor.h
> +    virtual void setFusedRotation(Quat r);
seems like you changed more than just adding threading, was this intended?

2024-03-28 13:44 UTC, TheDevMinerTV commented on src/sensors/mpu6050sensor.cpp
> +			setAcceleration(sfusion.getLinearAccVec());
same here

2024-03-28 13:44 UTC, TheDevMinerTV commented on src/sensors/icm42688sensor.cpp
> +    setAcceleration(sfusion.getLinearAccVec());
same here

2024-03-28 14:53 UTC, nekomona commented
Rebased after #314 merging

2024-03-28 14:54 UTC, TheDevMinerTV commented
Maybe we should put this behind a `#define`?

2024-03-28 15:09 UTC, nekomona commented
> Maybe we should put this behind a `#define`?

`#define` switches are up -w-

2024-03-28 15:12 UTC, TheDevMinerTV approved these changes

2024-10-30 18:04 UTC, Eirenliel requested changes

2024-10-30 18:04 UTC, Eirenliel commented on src/sensors/sensor.cpp
> +        networkConnection.sendRotationData(sensorId, &fusedRotation, DATA_TYPE_NORMAL, calibrationAccuracy);
```suggestion
        networkConnection.sendRotationData(sensorId, &lquat, DATA_TYPE_NORMAL, calibrationAccuracy);
```

Shouldn't it be like that?

Also can be combined my taking lquat out of the define and having the same sendRotationData be used.

2026-08-03 08:03 UTC, closed without merging