fshelper: fixed ESP8266 regression caused by abstracting FS access
SlimeVR/SlimeVR-Tracker-ESP pull request #321
Opened 2024-03-28 21:09 UTC by l0ud

This is hotfixing ESP8266 calibration storage which seems to be broken since #319 

isDirectory method on Dir object doesn't tell about the Dir object itself, but about the entry pointed by internal pointer (which you can move using next() to iterate). As next() is never called, isDirectory will always return false (in fact, isFile too).
Considering heavy simplifications in Esp8266 filesystem regarding directories and the fact that previous ESP8266 implementation didn't try to do any file/directory fixing, I made it ESP32 only.

2024-03-28 21:13 UTC, TheDevMinerTV commented
Thank you for catching this bug. I think that just leaving this check out from the ESP8266 code is the wrong move, as I wanted to implement that specific check for it as well. We should probably fix it "the right way".

2024-03-29 16:27 UTC, TheDevMinerTV approved these changes
LGTM

2024-03-29 16:28 UTC, TheDevMinerTV requested changes
As I said in the comment: ^

2024-03-29 18:10 UTC, Eirenliel approved these changes

2024-05-01 22:01 UTC, unlogisch04 commented
As this one seems to be stuck, i did open one with a fix that i tested on esp8266: https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/328

2024-05-04 15:45 UTC, l0ud commented
Superseded by: https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/328

2024-05-04 15:45 UTC, closed without merging