Dynamic Sfusion
SlimeVR/SlimeVR-Tracker-ESP pull request #363
Opened 2024-11-12 20:37 UTC by gorbit99

This PR makes the following changes:

1. IMU Support: adds support for icm45686, icm45605, and lsm6ds3 (non tr-c version), and also modifies the ICM42688 driver to use hires mode
2. Adds nonblocking calibration
    - The tracker detects when it's at rest and calibrates itself
    - The calibration is then used the next time the tracker starts up
    - This replaces manual calibration and is set as the default
 3. Adds per sensor VQF parameters, so each IMU can be fine tuned
 4. Enables VQF's MBE feature by default, and modifies VQF to be somewhat temperature aware
 5. Adds the DELCAL serial command to only delete the IMU calibration without having to delete WIFI data
 6. Adds 32 bit sensor sample support into sfusion
 7. Overclocks the ESP, so no fifo overruns happen

2024-11-12 21:35 UTC, Eirenliel requested changes
I'm not finished yet...

2024-11-12 21:35 UTC, Eirenliel commented on platformio-tools.ini
> +board_build.f_cpu = 160000000L
```suggestion
```
Do not overclock official slimes. We don't know how stable it is and how it changes power consumption and wi-fi characteristics.

2024-11-12 21:35 UTC, Eirenliel commented on platformio-tools.ini
> +board_build.f_cpu = 160000000L
```suggestion
```
Same as above.

2024-11-12 21:35 UTC, Eirenliel commented on src/debug.h
> +#define USE_NONBLOCKING_CALIBRATION
```suggestion
#define USE_NONBLOCKING_CALIBRATION true
```
Let's check defines to `true`, so we could set them to `false` too during compilation, for example.

2024-11-12 23:53 UTC, l0ud requested changes

2024-11-12 23:53 UTC, l0ud commented on src/sensors/softfusion/softfusionsensor.h
> +#if USE_NONBLOCKING_CALIBRATION
No C define blocks in softfusion core please :<
Should be separated as different (replaceable) calibration implementation, or at least separated in less spaghetti way :<

2024-11-12 23:53 UTC, l0ud commented on src/sensors/softfusion/softfusionsensor.h
> +#include "../nonblockingcalibration/NonBlockingCalibration.h"
This is subjective but I'm not the fan of "nonblocking" name for that. I think something like "auto" or "self-learning" is more descriptive for what it is.

2024-11-12 23:53 UTC, l0ud commented on src/sensors/nonblockingcalibration/AccelBiasCalibrationStep.h
> +
Not related strictly to the code, I would like to have some description (in PR I guess) about  how that autocalibration works (both gyro and especially accel).

2024-11-12 23:53 UTC, l0ud commented on src/sensors/softfusion/drivers/bmi270.h
> +	// and seems to work better than 0.1
It's neither 0.01 nor 0.1 for any sensor.

2024-12-10 08:49 UTC, Eirenliel approved these changes

2025-01-05 08:01 UTC, closed without merging