Glove
SlimeVR/SlimeVR-Tracker-ESP pull request #371
Opened 2024-12-07 13:47 UTC by Eirenliel

Pretty complex PR that changes how defines.h works, so it needs changes from all firmware tools @ButterscotchV @loucass003 

## Changes
- Abstract hardware interface for communicating with IMUs: can now easily add support for multiple pinouts, muxers, shifters, extenders, etc. by just adding a class file
  - Interfaces currently implemented: direct pin i2c, direct int pin, PCA9546A I2C expander, MCP23X17 GPIO expander
  - Sensor defines changed to SENSOR_DESC_LIST and SENSOR_DESC_ENTRY, and type of hardware interface is required. DIRECT_WIRE for directly connected I2C, DIRECT_PIN for directly connected INT. This is the breaking change for firmware tools.
- Send sensor position information (joint the seonsor controls, not 3d position) and sensor data type as defined in flex and glove PR's of the server
  - Position is set via new defines SENSOR_INFO_LIST and SENSOR_INFO_ENTRY, see examples in defines.h

## Defines changes

1. Maximum sensors count
```diff
- #define MAX_IMU_COUNT 2
+ #define MAX_SENSORS_COUNT 2
```
2. IMU list is now sensor list
```diff
- #define IMU_DESC_LIST \
+ #define SENSOR_DESC_LIST \
```
```diff
- IMU_DESC_ENTRY(...)
- SENSOR_DESC_ENTRY(...)
```
3. Sensor pinouts/hardware interface are now need to be wrapped in helpers:
```diff
- IMU_DESC_ENTRY(IMU,  PRIMARY_IMU_ADDRESS_ONE, IMU_ROTATION, PIN_IMU_SCL, PIN_IMU_SDA, PRIMARY_IMU_OPTIONAL, PIN_IMU_INT) 
+ SENSOR_DESC_ENTRY(IMU, PRIMARY_IMU_ADDRESS_ONE, IMU_ROTATION, DIRECT_WIRE(PIN_IMU_SCL, PIN_IMU_SDA), PRIMARY_IMU_OPTIONAL, DIRECT_PIN(PIN_IMU_INT), 0)
```
4. Following hardware interfaces supported:
  - `DIRECT_WIRE(scl, sda)` - I2C on GPIO
  - `PCA_WIRE(scl, sda, pca_addr, pca_channel)` - I2C on PCA9546A I2C expander
  - `DIRECT_PIN(pin)` - INT pin on GPIO
  - `MCP_PIN(pin)` - INT pin on MCP23X17 GPIO extender
  - `NO_PIN` - INT pin not used

## Test plan

There are a lot of changes, so we should do some testing before it's merged. I did some, but we need help with testing with other IMUs

* [x] Test with BNO085 glove + ESP32-C3 MCU + PCA9546A I2C extender + MCP23X17 GPIO extender
* [x] Test with official BNO085 slime and ESP12-F
* [ ] Test with official BNO085 slime + official BNO085 extension
* [ ] Test ESP32 with any IMU
* [ ] Test ESP32-C3 with any other IMU
* [ ] Test ESP12-F with any other IMU
* [ ] Test with BMI160
* [ ] Test with BMI270
* [ ] Test with LSM6DSV
* [ ] Test with ICM-42688
* [ ] Test with different IMU as extension compared to main
* [ ] Test with more than 2 IMUs on different I2C pins

I'm once again asking for help with testing!

Other important stuff:
* [ ] Prepare firmware tools for this change for FW 0.6.0+
* [ ] Bump firmware and protocol versions

2024-12-29 18:53 UTC, TheDevMinerTV requested changes
Please **rebase** to main and also move all of the unnecessary formatting commits into a different PR. It's impossible to review this PR otherwise.

2025-01-19 18:59 UTC, Eirenliel commented on src/main.cpp
> +		delay(60000);
Note to self: remove delay so OTA doesn't break.

2025-02-05 01:45 UTC, Eirenliel commented
@adabru sorry for not replying earilier. The discussion is currently in private channels.

It's out of scope how many sensors you would use, this PR adds support for multiplexing to have as many sensors as you might want. The actual skeleton computation is done on the server and it supports 1 to 3 sensors per finger.

This PR is also not the place to discuss actual glove design

2025-02-05 01:50 UTC, Eirenliel commented
> Please **rebase** to main and also move all of the unnecessary formatting commits into a different PR. It's impossible to review this PR otherwise.

Sorry but this needs to be reviewed as a whole, not as a history. A lot of changes were rethought during the development. If you can't review it, you can just not, it's fine.

2025-02-05 02:53 UTC, gorbit99 commented on lib/bno080/PinInterface.h
> +    virtual void digitalWrite(uint8_t val);
```suggestion
    virtual int digitalRead() = 0;
    virtual void pinMode(uint8_t mode) = 0;
    virtual void digitalWrite(uint8_t val) = 0;
```
I don't see any direct implementation for these, they should be pure virtual then.

2025-02-05 02:53 UTC, gorbit99 commented on lib/bno080/BNO080.h
> +	bool hasNewCliabrationStatus();
Nit: Typo

2025-02-05 02:53 UTC, gorbit99 commented on lib/bno080/PinInterface.h
> +#define _H_PIN_INTERFACE_
Idea: What do you think of potentially moving to #pragma once completely? I don't think I was born yet when that was fully supported by all compilers already

2025-02-05 02:53 UTC, gorbit99 commented on src/main.cpp
> +#endif
This was removed in a different PR (https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/329), I assume you mean the logs get cut off at the beginning? A ring buffer should be implemented for logs to solve this imo

2025-02-05 02:53 UTC, gorbit99 commented on src/network/connection.h
> +	// PACKET_FLEX_DATA 24
24? Below it has 26 for this packet

2025-02-05 02:53 UTC, gorbit99 commented on src/sensorinterface/I2CWireSensorInterface.cpp
> +		} else {
Negate and remove unnecessary branch

2025-02-05 02:53 UTC, gorbit99 commented on src/sensorinterface/I2CWireSensorInterface.cpp
> +			i2c_set_pin(I2C_NUM_0, sdaPin, sclPin, false, false, I2C_MODE_MASTER);
Q: I'm not very familiar with this part of the code, any reason this is suddenly doing esp-idf function calls instead of the arduino equivalent?

2025-02-05 02:53 UTC, gorbit99 commented on src/sensorinterface/MCP23X17PinInterface.h
> +	MCP23X17PinInterface(Adafruit_MCP23X17* mcp, uint8_t pin)
Definitely should be a reference

2025-02-05 02:53 UTC, gorbit99 commented on src/sensorinterface/SensorInterface.h
> +	virtual void swapIn();
```suggestion
	virtual void init() = 0;
	virtual void swapIn() = 0;
```

Should be pure virtual

2025-02-05 02:53 UTC, gorbit99 commented on src/sensors/ADCResistanceSensor.cpp
> +#if ESP32
```suggestion
#elif ESP32
```

Nit: combine

2025-02-05 02:53 UTC, gorbit99 commented on src/consts.h
> +	ADC_RESISTANCE,
Prolly should rename the enum at this point

2025-02-05 02:53 UTC, gorbit99 commented on src/sensors/ADCResistanceSensor.h
> +			new SlimeVR::EmptySensorInterface
Instead of new-ing it, it would be better to have a single global instance of the empty sensor interface and use that

2025-02-05 02:53 UTC, gorbit99 commented on src/sensors/SensorManager.cpp
> +#include <map>
Map is the slower of the two map variants, while this isn't part of any hot code paths, it also doesn't take much to swap it out to an unordered_map

2025-02-05 02:53 UTC, gorbit99 commented on src/sensors/SensorManager.cpp
> +	std::map<std::tuple<int, int, int, int>, I2CPCASensorInterface*> pcaWireInterfaces;
These don't need to be pointers, since they aren't stored as their base type

2025-02-05 02:53 UTC, gorbit99 commented on src/consts.h
> +#define TRACKER_TYPE_SVR_GLOVE_RIGHT 1
Should be enum classes

2025-02-05 02:53 UTC, gorbit99 commented on src/sensors/sensor.h
> +	std::shared_ptr<SlimeVR::SensorInterface> m_hwInterface;
this probably should be a unique_ptr, at least I don't see it being copied anywhere

2025-02-05 02:53 UTC, gorbit99 commented on src/sensors/sensorposition.h
> +#define GLOVE_RIGHT 2
Should be enum classes

2025-02-05 15:25 UTC, Eirenliel commented on src/main.cpp
> +#endif
See discord: doesn't work for me. actually getting no serial if i don't put the delay, and i couldn't figure out why yet.

2025-02-05 15:26 UTC, Eirenliel commented on src/sensorinterface/I2CWireSensorInterface.cpp
> +			i2c_set_pin(I2C_NUM_0, sdaPin, sclPin, false, false, I2C_MODE_MASTER);
This has been written by someone else and i moved it here. I'm not sure, I can investigate indepth it if it's important...

2025-02-05 15:27 UTC, Eirenliel commented on src/sensors/ADCResistanceSensor.h
> +			new SlimeVR::EmptySensorInterface
doesn't matter, it happens once and it's empty. instead of bothering with scope it's easier to do that, imo.

2025-02-05 22:18 UTC, Eirenliel commented on src/sensors/SensorManager.cpp
> +#include <map>
i tried and the constructor complained, so i just think it doesn't matter since it's not used in runtime

2025-02-05 22:19 UTC, Eirenliel commented on lib/bno080/BNO080.h
> +	uint8_t _calibrationResponseStatus, _accelCalEnabled, _gyroCalEnabled, _magCalEnabled, _planarAccelCalEnabled, _onTableCalEnabled;
i really don't want to dig through bno datashet rn, it's basically useless anyway...

2025-02-05 22:28 UTC, gorbit99 approved these changes
I'll try cleaning up my remaining complaints in a follow-up PR down the line

2025-02-06 15:46 UTC, merged